#!/bin/bash

while true 
do
	if [ -f "Judge/request.txt" ]; then
		while [ grep "|" "request.txt" ];
		do
			sleep 1
		done
		cd Judge
		./vader
		sleep 3
		cd ..
		./updateResult
	else 
		sleep 1
	fi
done
